specVersion: 0.0.2
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: LiquidityPool
    network: arbitrum-one
    source:
      address: "0x3e0199792Ce69DC29A0a36146bFa68bd7C8D6633"
      abi: LiquidityPool
      startBlock: 22266132
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - OpenPosition
        - ClosePosition
        - SetAssetParams
      abis:
        - name: LiquidityPool
          file: ./abis/LiquidityPool.json
      eventHandlers:
        - event: OpenPosition(indexed address,indexed uint8,(bytes32,uint8,bool,uint96,uint96,uint96,uint96,uint96,uint96,uint96))
          handler: handleOpenPosition
        - event: ClosePosition(indexed address,indexed uint8,(bytes32,uint8,uint8,bool,uint96,uint96,uint96,uint96,uint96,bool,uint96,uint96,uint96))
          handler: handleClosePosition
        - event: SetAssetParams(indexed uint8,bytes32,uint32,uint32,uint32,uint32,uint32,uint96,uint96,uint32,uint32)
          handler: handleSetAssetParams
      file: ./src/trade.ts
  - kind: ethereum/contract
    name: ReferralManager
    network: arbitrum-one
    source:
      address: "0xa68d96F26112377abdF3d6b9fcde9D54f2604C2a"
      abi: ReferralManager
      startBlock: 22266132
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - SetTiers
        - SetReferralCode
        - RegisterReferralCode
        - SetRebateRecipient
        - TransferReferralCode
      abis:
        - name: ReferralManager
          file: ./abis/ReferralManager.json
      eventHandlers:
        - event: SetTiers((uint8,uint64,uint64,uint64)[])
          handler: handleSetTier
        - event: SetReferralCode(address,bytes32)
          handler: handleSetReferralCode
        - event: RegisterReferralCode(address,bytes32)
          handler: handleRegisterReferralCode
        - event: SetRebateRecipient(bytes32,address,address)
          handler: handleSetRebateRecipient
        - event: TransferReferralCode(bytes32,address,address)
          handler: handleTransferReferralCode
      file: ./src/tier.ts
  - kind: ethereum/contract
    name: Disperse
    network: arbitrum-one
    source:
      address: "0x39A6567C3E01d28c37403c8782DE78490D9204fA"
      abi: Disperse
      startBlock: 22266132
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - DisperseReferrerRebate
        - DisperseTraderDiscount
        - Transfer
      abis:
        - name: Disperse
          file: ./abis/Disperse.json
      eventHandlers:
        - event: DisperseReferrerRebate(address,uint256,uint256,bytes32[],address[],uint256[],uint256)
          handler: handleDisperseReferrerRebate
        - event: DisperseTraderDiscount(uint256,uint256,address[],uint256[],uint256)
          handler: handleDisperseTraderDiscount
        - event: Transfer(uint8,bytes32,address,uint256)
          handler: handleTransfer
      file: ./src/disperse.ts
